kind: Deployment
apiVersion: apps/v1
metadata:
  name: tsv-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: tsv-nodejs
          image: nodejs-image:latest
          ports:
            - name: http
              containerPort: 16001
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: tsv-nodejs-svc
spec:
  ports:
    - name: http-16001
      port: 16001
      protocol: TCP
      targetPort: 16001
  selector:
    app: nodejs-app
